"""
SOP Generator Module
Generates structured Standard Operating Procedure documents
from a process description or JSON template.
"""

import json
from datetime import datetime
from pathlib import Path

SOP_TEMPLATE = """# {title}

**Document ID:** {doc_id}
**Version:** {version}
**Effective Date:** {date}
**Department:** {department}
**Author:** {author}
**Review Cycle:** {review_cycle}

---

## 1. Purpose

{purpose}

---

## 2. Scope

{scope}

---

## 3. Responsibilities

{responsibilities}

---

## 4. Definitions

{definitions}

---

## 5. Procedure

{procedure}

---

## 6. Quality Checks

{quality_checks}

---

## 7. Exception Handling

{exceptions}

---

## 8. Documentation & Records

{documentation}

---

## 9. References

{references}

---

## 10. Revision History

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| {version} | {date} | {author} | Initial version |

---
*Generated by OpsCore SOP Generator*
"""

def generate_from_dict(data: dict) -> str:
    """Generate SOP from a structured dict."""
    def format_list(items):
        if isinstance(items, list):
            return "\n".join(f"- {item}" for item in items)
        return str(items)

    def format_steps(steps):
        if isinstance(steps, list):
            out = []
            for i, step in enumerate(steps, 1):
                if isinstance(step, dict):
                    title = step.get("step", f"Step {i}")
                    desc  = step.get("description", "")
                    note  = step.get("note", "")
                    out.append(f"### Step {i}: {title}\n{desc}")
                    if note:
                        out.append(f"> **Note:** {note}")
                else:
                    out.append(f"### Step {i}\n{step}")
            return "\n\n".join(out)
        return str(steps)

    return SOP_TEMPLATE.format(
        title         = data.get("title", "Standard Operating Procedure"),
        doc_id        = data.get("doc_id", f"SOP-{datetime.now().strftime('%Y%m%d')}"),
        version       = data.get("version", "1.0"),
        date          = data.get("date", datetime.now().strftime("%Y-%m-%d")),
        department    = data.get("department", "Operations"),
        author        = data.get("author", "Operations Team"),
        review_cycle  = data.get("review_cycle", "Annually"),
        purpose       = data.get("purpose", ""),
        scope         = format_list(data.get("scope", [])),
        responsibilities = format_list(data.get("responsibilities", [])),
        definitions   = format_list(data.get("definitions", [])),
        procedure     = format_steps(data.get("procedure", [])),
        quality_checks = format_list(data.get("quality_checks", [])),
        exceptions    = format_list(data.get("exceptions", [])),
        documentation = format_list(data.get("documentation", [])),
        references    = format_list(data.get("references", [])),
    )

def generate_from_description(title: str, description: str, author="Nnaemeka Duru", dept="Operations") -> str:
    """Generate a basic SOP from a plain text description."""
    lines = [l.strip() for l in description.strip().split("\n") if l.strip()]
    steps = [{"step": f"Step {i+1}", "description": line} for i, line in enumerate(lines)]

    data = {
        "title": title,
        "department": dept,
        "author": author,
        "purpose": f"This SOP defines the procedure for: {title.lower()}.",
        "scope": [f"Applies to all {dept} team members involved in {title.lower()}."],
        "responsibilities": [
            f"Operations Manager: Ensure this SOP is followed and kept current.",
            f"Team Members: Follow all steps as defined in this document.",
            f"Supervisor: Conduct regular compliance checks.",
        ],
        "definitions": ["N/A — refer to department glossary for standard terms."],
        "procedure": steps,
        "quality_checks": [
            "Verify all steps have been completed before sign-off.",
            "Document any deviations in the exceptions log.",
            "Escalate unresolved issues to the supervisor within 2 hours.",
        ],
        "exceptions": [
            "System downtime: switch to manual backup process and notify supervisor immediately.",
            "Missing data: flag for review, do not proceed with incomplete information.",
        ],
        "documentation": [
            "Log completion in the daily operations tracker.",
            "File physical records in the designated department folder.",
            "Update digital records within 24 hours of task completion.",
        ],
        "references": [
            "Company Operations Handbook",
            "Department Policy Manual",
        ],
    }
    return generate_from_dict(data)

def run(source, output_dir=None, author="Nnaemeka Duru", dept="Operations"):
    """
    source: path to JSON file or plain text description
    Returns: path to generated SOP file
    """
    output_dir = Path(output_dir or ".")
    output_dir.mkdir(parents=True, exist_ok=True)

    path = Path(source)
    if path.exists() and path.suffix == ".json":
        print(f"\n[SOP] Generating from JSON template: {source}")
        with open(path) as f:
            data = json.load(f)
        title = data.get("title", "SOP")
        content = generate_from_dict(data)
    else:
        # Treat as description text
        title = source[:50] if len(source) < 80 else "Standard Operating Procedure"
        print(f"\n[SOP] Generating from description: '{title[:40]}...'")
        content = generate_from_description(title, source, author=author, dept=dept)

    slug = title.lower().replace(" ", "_")[:40]
    out_path = output_dir / f"SOP_{slug}_{datetime.now().strftime('%Y%m%d')}.md"
    out_path.write_text(content)
    print(f"  ✅ SOP saved → {out_path}")
    return str(out_path)
